"""Manual abstract-level scores for the pair-first dataset. idx = row index in candidate_papers.jsonl
(after dropping the Severe/Moderate hemophilia A subtype pair). Dims: P phenotype, G genetic, M mechanism,
T therapeutic, N natural_history, D diagnostic_confusability, C comorbidity; values are (weight, score)."""
# idx: (finding, {dim: (weight, score)}); dims P=phenotype G=genetic M=mechanism T=therapeutic N=natural_history D=diagnostic_confusability C=comorbidity
S={
0:("HPT-JT families linked to HRPT2 locus; parathyroid carcinoma is a component tumour of the syndrome",{'P':(.2,.5),'G':(.4,.75),'C':(.4,.75)}),
1:("CDC73/HRPT2 loss implicated in both HPT-JT and sporadic parathyroid carcinoma",{'G':(.5,.6),'M':(.5,.6)}),
3:("French cohort: germline HRPT2/CDC73 deletions in HPT-JT, which can present with parathyroid adenoma or carcinoma",{'G':(.5,.75),'C':(.5,.75)}),
4:("Same CDC73 gene mutated somatically in ~70% of parathyroid carcinoma and germline in HPT-JT",{'G':(.7,.75),'M':(.3,.6)}),
6:("Parathyroid carcinoma arises sporadically or within HPT-JT via CDC73 germline mutations",{'G':(.6,.75),'M':(.2,.6),'C':(.2,.6)}),
7:("Parathyroid carcinoma accounts for up to 15% of hereditary HPT-JT cases; CDC73 mutations dominate",{'G':(.5,.75),'C':(.5,.6)}),
8:("GNAS locus underlies both PHP1A (Gs-alpha mutations) and PHP1B (imprinting defects)",{'G':(.6,.75),'M':(.4,.5)}),
9:("Early-onset obesity found in PHP1A and PHP1B, both caused by GNAS defects but treated as distinct entities",{'P':(.4,.6),'G':(.4,.75),'M':(.2,.6)}),
10:("PHP1A due to GNAS deletion with apparent loss of methylation, mimicking PHP1B epigenetics",{'P':(.2,.6),'G':(.5,.75),'D':(.3,.7)}),
11:("Chinese PHP1 cohort: growth and short-stature patterns across PHP1A/1B genotypes",{'P':(.6,.75),'N':(.4,.75)}),
12:("Novel GNAS exon 1 deletion causes PHP1A without the methylation changes seen in PHP1B",{'P':(.3,.75),'G':(.5,.6),'D':(.2,.6)}),
13:("Thyroid dysgenesis review: athyreosis and hypoplasia as defects of thyroid development",{'P':(.3,.75),'G':(.3,.6),'M':(.4,.75)}),
14:("TSHR mutations in siblings with congenital hypothyroidism and apparent athyreosis versus hypoplasia",{'G':(.5,.6),'D':(.5,.75)}),
15:("Monogenic defects associate with athyreosis and orthotopic hypoplasia within thyroid dysgenesis",{'G':(.5,.75),'M':(.5,.6)}),
19:("Ultrasound and scintigraphy separate athyreosis, ectopia and hypoplasia in congenital hypothyroidism",{'P':(.4,.75),'D':(.6,.75)}),
20:("TSHR variant studied across hypoplasia, hemiagenesis, athyreosis and ectopy cohort",{'P':(.4,.6),'G':(.6,.6)}),
21:("30 holoprosencephaly families: lobar versus alobar sex distribution and recurrence risk",{'P':(.5,.75),'N':(.5,.75)}),
22:("PTCH mutations produce alobar and lobar holoprosencephaly, even with the same mutation",{'P':(.4,.75),'G':(.6,.75)}),
23:("Dysgenesis of the deep venous system as angiographic diagnostic criterion across HPE types",{'P':(.4,.75),'D':(.6,.75)}),
28:("Pituitary dysfunction and outcome in congenital midline defects including semilobar and lobar HPE",{'N':(.5,.6),'C':(.5,.6)}),
29:("Clinical and angiographic features of alobar, semilobar and lobar holoprosencephaly",{'P':(.5,.75),'D':(.5,.75)}),
30:("Aqueductal atresia in semilobar and lobar holoprosencephaly cases",{'P':(.6,.6),'C':(.4,.5)}),
34:("Thyroid ectopia and athyreosis as the two main forms of thyroid dysgenesis; shared morphogenesis defects",{'P':(.4,.75),'M':(.6,.75)}),
36:("Ultrasound and isotope scanning to distinguish ectopia from athyreosis in infants with raised TSH",{'P':(.2,.5),'D':(.8,.6)}),
37:("Initial biochemical severity differs between athyreosis and ectopia and by sex",{'P':(.7,.5),'D':(.3,.5)}),
38:("ILAE definitions of idiopathic generalized epilepsy syndromes incl. juvenile absence and juvenile myoclonic",{'P':(.4,.75),'G':(.2,.6),'D':(.4,.6)}),
39:("Photosensitivity is closely tied to juvenile absence and juvenile myoclonic epilepsy among generalised epilepsies",{'P':(1.0,.6)}),
44:("Voxel-based morphometry in IGE subsyndromes incl. juvenile absence and JME; limits between subsyndromes ill-defined",{'P':(.5,.75),'M':(.5,.75)}),
45:("Quantitative MRI shows widespread structural change across idiopathic generalized epilepsies",{'P':(.4,.75),'M':(.6,.75)}),
46:("GCD2 families with GCD1-like phenotype in daughters; same TGFBI gene",{'P':(.4,.75),'G':(.3,.9),'D':(.3,.75)}),
47:("TGFBI H626P and other mutations give overlapping corneal dystrophy phenotypes in Czech families",{'P':(.5,.5),'G':(.5,.75)}),
48:("Early alcohol exposure proposed as cause of alobar and semilobar holoprosencephaly",{'P':(.5,.75),'M':(.5,.75)}),
49:("Brainstem tract diffusion MRI correlates with forebrain malformation severity across HPE types",{'P':(.5,.75),'N':(.5,.5)}),
50:("Fetal MRI of cerebral malformations including alobar and semilobar HPE versus sonography",{'P':(.2,.75),'D':(.8,.6)}),
52:("Whirlin (DFNB31) linked to USH2; USH1/USH2 proteins interact in a shared network",{'G':(.6,.5),'M':(.4,.75)}),
53:("Prevalence and subtype distribution of Usher syndrome in Germany",{'P':(.2,.75),'N':(.8,.5)}),
54:("Relative frequencies of USH1 and USH2 among syndromic RP families in Spain",{'N':(1.0,.5)}),
55:("CDH23 (an USH1 gene) splice variants in a patient diagnosed with USH2",{'G':(.6,.6),'D':(.4,.5)}),
56:("MYO7A (USH1) and USH2A (USH2) account for most cases of their respective types",{'P':(.3,.75),'G':(.7,.25)}),
58:("Turkish Usher cohort: subtype epidemiology and MYO7A/PCDH15/USH2A etc. genes",{'G':(.5,.25),'N':(.5,.5)}),
61:("Turkish Usher cohort: USH2 and USH3 subtype epidemiology and genes",{'G':(.5,.25),'N':(.5,.5)}),
62:("Turkish Usher cohort: USH1 and USH3 subtype epidemiology and genes",{'G':(.5,.25),'N':(.5,.5)}),
63:("Genetics of primary aldosteronism reviews familial hyperaldosteronism types and causative genes",{'G':(.6,.5),'M':(.4,.5)}),
64:("Amsterdam-I families without MMR deficiency have lower cancer incidence than Lynch families",{'G':(.4,.25),'N':(.6,.25)}),
65:("Lynch syndrome and its mimics: MMR-deficient versus MMR-proficient familial CRC",{'G':(.4,.25),'M':(.2,.25),'D':(.4,.75)}),
66:("FCCTX is the MMR-proficient half of Amsterdam-defined HNPCC, distinct from Lynch syndrome",{'G':(.4,.25),'N':(.3,.5),'D':(.3,.75)}),
67:("MMR deficiency testing separates Lynch syndrome from other HNPCC conditions",{'M':(.5,.25),'D':(.5,.75)}),
68:("HNPCC splits into MMR-deficient (Lynch) and MMR-proficient (FCCTX) subsets",{'P':(.3,.75),'G':(.4,.25),'M':(.3,.25)}),
70:("Distinct tumour gene-expression signatures in Lynch syndrome versus FCCTX",{'G':(.3,.25),'M':(.7,.25)}),
76:("Erythropoietic porphyrias (CEP, HEP, EPP): animal models and gene-based therapies",{'M':(.4,.75),'T':(.6,.75)}),
78:("Photocutaneous porphyrias in childhood (CEP vs protoporphyria) distinguished by heme precursor profile",{'P':(.5,.75),'D':(.5,.75)}),
82:("Wnt signalling underlies rare genetic eye diseases such as Norrie disease and vascular disease such as ROP",{'G':(.2,.75),'M':(.8,.75)}),
83:("Ndph knockout shows angiogenic pathways shared by Norrie disease, ROP and Coats disease",{'P':(.3,.5),'M':(.7,.75)}),
84:("Norrie disease gene missense mutations tested in advanced ROP",{'P':(.4,.5),'G':(.6,.5)}),
85:("NDP mutations contribute to Norrie, FEVR, Coats and ROP, which are clinically similar",{'P':(.2,.6),'G':(.5,.5),'D':(.3,.6)}),
86:("NDP dinucleotide-repeat mutations screened in 100 premature infants with advanced ROP",{'G':(1.0,.5)}),
87:("FZD4 (Wnt receptor) variants associated with vitreoretinopathies and ROP",{'G':(.5,.5),'M':(.5,.75)}),
88:("MVA syndrome carries high malignancy risk, including embryonal tumours",{'N':(.3,.5),'C':(.7,.5)}),
90:("MEN1 locus mapped to chromosome 11 and lost in insulinoma tumours from MEN1 brothers",{'G':(.6,.75),'M':(.4,.75)}),
96:("Beta-cell-specific Men1 ablation in mice causes insulinoma",{'G':(.3,.75),'M':(.7,.75)}),
97:("Menin loss drives MEG3/c-MET epigenetic changes in MEN1-associated pancreatic NETs",{'G':(.2,.5),'M':(.8,.5)}),
98:("Retinitis pigmentosa genes review: RP occurs as part of syndromes such as Bardet-Biedl",{'P':(.5,.5),'G':(.5,.5)}),
99:("Cardinal BBS features: severe retinal dystrophy, only 2 of 28 had typical RP",{'P':(1.0,.5)}),
102:("Retinal ciliopathies span isolated retinal degeneration (RP) to syndromic forms such as BBS",{'P':(.4,.5),'M':(.6,.75)}),
106:("Hearing loss across FGFR-related craniosynostosis syndromes incl. Apert and Jackson-Weiss",{'P':(.5,.75),'G':(.5,.75)}),
107:("Fetal craniosynostosis case: differential diagnosis among Apert, Jackson-Weiss and related syndromes",{'P':(.3,.5),'D':(.7,.5)}),
108:("Digenic inheritance of juvenile/early-onset glaucoma: MYOC, CYP1B1, PITX2 in congenital and juvenile cases",{'P':(.3,.5),'G':(.7,.5)}),
109:("Population incidence of childhood glaucoma subtypes in Olmsted County",{'P':(.4,.5),'N':(.6,.5)}),
111:("Combined trabeculotomy-trabeculectomy outcomes across congenital and juvenile developmental glaucomas",{'P':(.2,.5),'T':(.8,.5)}),
112:("Trabeculotomy outcomes by onset group: congenital, infantile, juvenile developmental glaucoma",{'P':(.2,.5),'T':(.8,.5)}),
113:("Dallas registry: epidemiology and characteristics of childhood glaucoma subtypes",{'P':(.4,.5),'N':(.6,.5)}),
115:("Null CYP1B1 genotypes cause primary congenital and nondominant juvenile glaucoma",{'P':(.3,.5),'G':(.7,.75)}),
116:("Recurrence rates after surgery differ between prolactinoma and acromegaly",{'T':(.5,.5),'N':(.5,.5)}),
119:("Quality-of-life Z-scores compared between pituitary adenoma types including prolactinoma and acromegaly",{'P':(.4,.25),'N':(.6,.5)}),
120:("SF-36 quality of life across pituitary adenoma types incl. acromegaly and prolactinoma",{'P':(.4,.25),'N':(.6,.5)}),
121:("Cancer incidence in prolactinoma versus acromegaly, which favours neoplasia",{'N':(.3,.5),'C':(.7,.5)}),
126:("Neurosarcoidosis with hypothalamic destruction producing hypocretin-deficient narcolepsy type 1",{'M':(.5,.5),'C':(.5,.75)}),
127:("FGFR2 codon 290 mutation in severe Pfeiffer type 2, the same codon as Crouzon mutations",{'P':(.3,.75),'G':(.7,.9)}),
128:("Pfeiffer type 2 delineation; FGFR2 mutations shared with Crouzon/other subtypes",{'P':(.6,.5),'G':(.4,.75)}),
129:("FGFR1-3 analysis in Crouzon, Pfeiffer-2, Jackson-Weiss and Muenke syndromes",{'G':(1.0,.75)}),
130:("IRF6 mutations cause Van der Woude and predispose to isolated cleft lip/palate",{'G':(.7,.75),'M':(.3,.75)}),
131:("IRF6 variants cause syndromic clefting and contribute to isolated cleft lip/palate risk via GRHL3 network",{'G':(.5,.75),'M':(.5,.75)}),
132:("Van der Woude lip pits case; isolated cleft is one variable manifestation of the syndrome",{'P':(.6,.75),'D':(.4,.6)}),
133:("IRF6-related disorders span isolated cleft lip/palate to Van der Woude and popliteal pterygium syndromes",{'P':(.5,.75),'G':(.5,.9)}),
134:("ILAE classification of childhood-onset epilepsy syndromes incl. SeLECTS and CAE",{'P':(.5,.25),'D':(.5,.5)}),
135:("Multivariate rs-fMRI localises syndrome-specific epileptic networks in SeLECTS and CAE",{'M':(1.0,.25)}),
136:("Shared and divergent neuromagnetic network signatures in CAE and SeLECTS",{'P':(.3,.25),'M':(.7,.5)}),
137:("Processing speed, thalamic and somatomotor correlates in SeLECTS and CAE",{'M':(.5,.5),'N':(.5,.5)}),
139:("Distinct dynamic functional network connectivity patterns in SeLECTS versus CAE",{'M':(1.0,.25)}),
140:("Boc and Gas1 modify the holoprosencephaly spectrum; microforms are the mildest manifestation",{'P':(.2,.75),'G':(.4,.75),'M':(.4,.75)}),
}
