"""Manual abstract-level scores for the v2 (feature-stratified) dataset. idx = row index in candidate_papers_v2.jsonl.
Dims: P phenotype, G genetic, M mechanism, T therapeutic, N natural_history, D diagnostic_confusability, C comorbidity;
values are (weight, score). Scores follow the rubric anchors 0 / .25 / .5 / .75 / 1; papers that only mention the
pair in passing are left out."""
S={}
S.update({
0:("Global PKU genetic landscape and epidemiology; PKU and mild HPA are allelic PAH disorders",{'P':(.3,.75),'G':(.5,1.0),'N':(.2,.75)}),
1:("PAH mutation spectrum in US cohort spanning PKU to mild hyperphenylalaninemia",{'P':(.3,.75),'G':(.7,1.0)}),
2:("PAH genotype-phenotype correlation across PKU and milder hyperphenylalaninemia in Fujian cohort",{'P':(.5,.75),'G':(.5,1.0)}),
3:("European multicentre study: PKU and mild HPA are allelic; genotype predicts metabolic phenotype",{'P':(.5,.75),'G':(.5,1.0)}),
4:("Gut microbiota differs between diet-treated PKU children and MHP children not on diet",{'M':(.4,.5),'T':(.6,.25)}),
5:("TREX1 mutations underlie cerebroretinal vasculopathy, HVR and HERNS, now grouped as RVCL",{'G':(.6,1.0),'M':(.4,.9)}),
6:("Hereditary vascular retinopathy linked to 3p21, same locus as cerebroretinal vasculopathy and HERNS",{'P':(.4,.75),'G':(.6,1.0)}),
7:("CRV, HERNS and HVR map to the same 3p21 locus; distinct from hereditary retinal arteriolar tortuosity",{'P':(.5,.75),'G':(.5,1.0)}),
8:("CRV and HVR/HERNS/HSA neuropathology and genetics unified as RVCL",{'P':(.5,.75),'G':(.5,1.0)}),
11:("Spermatocytic seminoma must be distinguished from classic seminoma and other germ cell tumours; indolent course, orchiectomy suffices",{'D':(.6,.5),'T':(.4,.25)}),
13:("ITGCN absent in spermatocytic seminoma and infantile yolk sac tumour, both more benign and developmentally distinct from adult TGCT",{'M':(.6,.75),'N':(.4,.75)}),
14:("OCT3/4 upstream methylation differs across testicular germ cell tumour types incl. yolk sac tumour and spermatocytic seminoma",{'G':(.4,.5),'M':(.6,.5)}),
17:("Selinexor preclinical activity across sarcoma subtypes incl. alveolar soft part sarcoma and leiomyosarcoma",{'T':(1.0,.5)}),
18:("Checkpoint inhibitor efficacy in metastatic soft-tissue sarcoma subtypes incl. ASPS and leiomyosarcoma",{'T':(1.0,.5)}),
19:("Vibratory angioedema is a subtype of vibratory urticaria; systematic review of features and treatment",{'P':(.6,.9),'T':(.4,.75)}),
20:("Acquired vibratory urticaria/angioedema case responding to omalizumab",{'P':(.6,.9),'T':(.4,.9)}),
21:("NEU1 variants in sialidosis: type 1 (mild) versus type 2 (severe) by catalytic activity",{'P':(.5,.5),'G':(.5,1.0)}),
22:("Sialidosis type 1 milder late-onset versus type 2 early-onset dysmorphic form, same NEU1 gene",{'P':(.6,.5),'G':(.4,1.0)}),
27:("EWSR1-NFATC2 sarcoma overlaps immunomorphologically with Ewing sarcoma and extraskeletal myxoid chondrosarcoma",{'G':(.4,.5),'D':(.6,.5)}),
28:("Prefrontal network disconnection in both bvFTD and semantic dementia",{'P':(.5,.75),'M':(.5,.75)}),
29:("Semantic dementia in a patient with MAPT V363I, a gene usually linked to other FTD presentations",{'P':(.5,.5),'G':(.5,.5)}),
30:("CSF proteomics and biomarkers across FTLD clinical variants (bvFTD, SD, PNFA)",{'D':(.4,.5),'M':(.6,.75)}),
31:("Classification and diagnosis of frontotemporal lobar degenerations: bvFTD, PNFA, semantic dementia as distinct syndromes of one spectrum",{'P':(.4,.75),'G':(.3,.75),'D':(.3,.5)}),
32:("RYR1 mutations in malignant hyperthermia, central core disease and multiminicore disease",{'G':(.7,1.0),'C':(.3,.75)}),
33:("Epigenetic RYR1 allele silencing reveals recessive mutations in core myopathies",{'G':(.7,1.0),'M':(.3,.75)}),
34:("RYR1 variant landscape in Singapore; CCD, MmD, CFTD and MH share the gene",{'G':(.6,1.0),'N':(.4,.5)}),
35:("Core myopathies (central core, multiminicore) and malignant hyperthermia risk",{'P':(.2,.75),'G':(.2,1.0),'C':(.6,.75)}),
36:("RYR1 mutations in over 90% of central core disease; rarer in multiminicore disease",{'P':(.2,.6),'G':(.8,.75)}),
39:("lncRNA biomarker panel to discriminate hepatoblastoma, hepatocellular adenoma and other liver tumours",{'M':(.4,.25),'D':(.6,.25)}),
43:("Michels, Carnevale, OSA and Malpuech syndromes proposed as variable expression of a single entity",{'P':(.6,.9),'G':(.4,.9)}),
44:("Oto-palato-digital syndrome variable clinical expression across type I and II",{'P':(1.0,.9)}),
45:("P2RY5 mutations in autosomal recessive hypotrichosis simplex with woolly hair",{'P':(.5,.75),'G':(.5,.75)}),
46:("Novel locus for AD hypotrichosis simplex with woolly hair; HS with/without woolly hair is one disorder group",{'P':(.4,.75),'G':(.6,.5)}),
47:("LIPH mutations cause AR hypotrichosis simplex with woolly hair",{'P':(.5,.75),'G':(.5,.75)}),
48:("P2RY5 mutations in hypotrichosis simplex with woolly hair in Turkish and Indian patients",{'P':(.5,.75),'G':(.5,.75)}),
})
S.update({
50:("POMT1 mutations in Walker-Warburg syndrome; MEB and FCMD present a similar combination of symptoms with different genes",{'P':(.5,.75),'G':(.5,.5)}),
52:("TMEM5 and ISPD mutations in cobblestone lissencephaly, a continuum covering WWS and MEB",{'P':(.5,.75),'G':(.5,.75)}),
53:("Brain dystroglycan deletion models the brain defects of FCMD, MEB and Walker-Warburg syndrome",{'P':(.2,.75),'M':(.8,.75)}),
55:("Social cognition and structural neuroimaging in progressive non-fluent aphasia versus bvFTD",{'P':(.6,.5),'M':(.4,.5)}),
56:("Verb comprehension deficits across frontotemporal degeneration variants",{'P':(1.0,.5)}),
58:("CSF proteomics and biomarkers across FTLD clinical variants (bvFTD, PNFA, SD)",{'D':(.4,.5),'M':(.6,.75)}),
62:("Porokeratosis review: Mibelli and DSAP variants share the defective isoprenoid pathway and cornoid lamella",{'P':(.3,.75),'G':(.3,.9),'M':(.4,.9)}),
63:("Singapore porokeratosis series: immunosuppression, phototherapy and malignant progression across subtypes",{'P':(.4,.75),'N':(.6,.75)}),
64:("Follicular porokeratosis as histologic variant of DSAP and other porokeratosis subtypes",{'P':(.7,.75),'D':(.3,.75)}),
65:("MVK splicing mutation causes porokeratosis of Mibelli; MVK also implicated in DSAP",{'P':(.4,.75),'G':(.6,.9)}),
66:("DSAP case report placing it among porokeratosis variants incl. Mibelli",{'P':(1.0,.75)}),
68:("Acetazolamide-responsive myotonia differs from typical dominant/recessive myotonia congenita",{'P':(.5,.5),'D':(.5,.5)}),
69:("Atypical potassium-sensitive myotonia congenita linked to sodium channel locus rather than chloride channel",{'P':(.3,.5),'G':(.7,.25)}),
70:("SCN4A Ile239Thr in acetazolamide-responsive sodium channel myotonia, distinguished from myotonia congenita",{'G':(.5,.25),'D':(.5,.5)}),
72:("ACOG guidance on women with PAH deficiency: maternal PKU risk depends on phenylalanine level, incl. mild hyperphenylalaninemia",{'T':(.5,.5),'C':(.5,.75)}),
74:("Pediatric mastocytosis presents as solitary mastocytoma, urticaria pigmentosa or diffuse disease",{'P':(.5,.75),'N':(.5,.75)}),
75:("Pediatric mastocytosis review: urticaria pigmentosa, diffuse cutaneous and mastocytoma forms",{'P':(.4,.75),'N':(.3,.75),'T':(.3,.75)}),
76:("Cutaneous mastocytosis forms (UP, mastocytoma, TMEP) as signs of underlying systemic mastocytosis",{'P':(.5,.75),'C':(.5,.75)}),
77:("Recognition and management of pediatric cutaneous mastocytosis forms",{'P':(.5,.75),'T':(.5,.75)}),
79:("Cancer incidence lower in Amsterdam-I families without MMR deficiency (FCCTX) than in Lynch families",{'G':(.4,.25),'N':(.6,.25)}),
80:("HNPCC splits into MMR-deficient (Lynch) and MMR-proficient (FCCTX) subsets",{'P':(.3,.75),'G':(.4,.25),'M':(.3,.25)}),
81:("Lynch syndrome and Lynch syndrome mimics: MMR-deficient versus MMR-proficient familial CRC",{'G':(.4,.25),'M':(.2,.25),'D':(.4,.75)}),
83:("FCCTX is the MMR-proficient half of Amsterdam-defined HNPCC, distinct from Lynch syndrome",{'G':(.4,.25),'N':(.3,.5),'D':(.3,.75)}),
84:("Schaaf-Yang syndrome (MAGEL2) overlaps Prader-Willi in infancy but diverges in childhood",{'P':(.5,.5),'G':(.3,.75),'N':(.2,.5)}),
85:("MAGEL2 variants produce Chitayat-Hall, Schaaf-Yang and Prader-Willi phenotypes with overlap",{'P':(.4,.5),'G':(.6,.75)}),
86:("MAGEL2 and L1CAM mutations in hypopituitarism with arthrogryposis; SYS phenotypically overlaps PWS",{'P':(.6,.5),'G':(.4,.5)}),
87:("MAGEL2-deubiquitinase complex; MAGEL2 truncation in SYS and deletion in PWS both cause sleep abnormalities",{'G':(.4,.75),'M':(.6,.75)}),
88:("PWS and Schaaf-Yang syndrome intersect at MAGEL2 in the 15q11-q13 region",{'P':(.2,.5),'G':(.5,.75),'M':(.3,.75)}),
89:("Mechanisms and management of inherited channelopathies (LQTS, Brugada, CPVT, short QT)",{'M':(.5,.5),'T':(.5,.5)}),
90:("ICD versus medical therapy for cardiac channelopathies incl. CPVT and short QT",{'T':(1.0,.5)}),
91:("Cardiovascular manifestations of Marfan and related TGFB-signalling diseases incl. aneurysm-osteoarthritis syndrome",{'P':(.4,.75),'G':(.2,.5),'M':(.4,.75)}),
93:("Familial caudal dysgenesis sibs with varying degrees up to sirenomelia; evidence of a dominant gene",{'P':(.6,.9),'G':(.4,.75)}),
94:("Regorafenib activity differs across bone sarcoma cohorts incl. Ewing sarcoma and chondrosarcoma",{'T':(1.0,.25)}),
97:("Immune checkpoint inhibitors in bone sarcomas incl. Ewing sarcoma and chondrosarcoma",{'T':(1.0,.25)}),
})
S.update({
100:("TGFb-signalling aortopathies: Loeys-Dietz and aneurysm-osteoarthritis syndrome share cardiovascular phenotype with Marfan",{'P':(.4,.75),'G':(.2,.5),'M':(.4,.75)}),
101:("p63 amino-terminal truncating mutations in RHS/AEC-like patients reveal translation re-initiation",{'G':(.5,1.0),'M':(.5,.9)}),
103:("TP63 R337L in split-hand/foot with hypodontia; TP63 disorders incl. AEC and Rapp-Hodgkin",{'P':(.3,.6),'G':(.7,1.0)}),
104:("AEC and Rapp-Hodgkin syndromes are a clinical continuum caused by TP63; craniofacial phenotype of 17 AEC patients",{'P':(.5,.9),'G':(.5,1.0)}),
105:("Rapp-Hodgkin and AEC syndrome: same entity? Same defects, AEC adds ankyloblepharon and scalp dermatitis",{'P':(.7,.9),'D':(.3,.9)}),
108:("BMI differs between PHP1a (maternal GNAS) and PPHP (paternal GNAS), both AHO",{'P':(.5,.75),'G':(.3,1.0),'M':(.2,.75)}),
109:("Cognitive impairment prevalent in PHP-Ia but not PPHP despite both having AHO",{'P':(.8,.25),'M':(.2,.75)}),
110:("Novel GNAS1 deletions in AHO kindreds with PPHP and PHP-Ia members",{'P':(.4,.75),'G':(.6,1.0)}),
111:("GNAS1 molecular analysis for correct diagnosis of AHO: mutations in both PHP-Ia and PPHP",{'G':(.5,1.0),'D':(.5,.75)}),
112:("AHO with del(2q37.3): PHP and PPHP biochemical variants",{'P':(.5,.75),'G':(.5,.25)}),
113:("Clinical, genetic and pathological heterogeneity of FTD: SD and PNFA within the FTLD spectrum",{'P':(.4,.75),'G':(.3,.75),'M':(.3,.75)}),
114:("Early-onset dementia clinical diagnostic accuracy against post-mortem pathology (FTD subtypes)",{'D':(1.0,.5)}),
115:("Ubiquitin pathology subtypes in FTLD-U relate to clinical syndromes incl. SD and PNFA",{'P':(.4,.5),'M':(.6,.5)}),
116:("FTLD pathogenesis and pathways to phenotype across bvFTD, SD and PNFA",{'P':(.3,.75),'M':(.7,.75)}),
117:("C9ORF72 expansion carriers across FTD, PNFA and SD show distinct clinical and pathological features",{'P':(.5,.5),'G':(.5,.5)}),
118:("Congenital cranial dysinnervation disorders spectrum incl. Duane retraction syndrome and congenital ptosis; TUBB6",{'P':(.3,.5),'G':(.2,.5),'M':(.5,.75)}),
120:("Duane retraction syndrome and accompanying ocular abnormalities incl. ptosis",{'P':(1.0,.5)}),
121:("Linkage of familial melanoma locus MLM to 9p13-p22 in melanoma kindreds",{'P':(.2,.75),'G':(.8,.75)}),
122:("Chromosome 9p linkage in CMM/dysplastic nevi families with genetic heterogeneity",{'G':(1.0,.75)}),
123:("p16CDKN2 temperature-sensitive mutants in familial melanoma",{'G':(.4,.75),'M':(.6,.75)}),
124:("Rare POT1 missense variants predispose to familial melanoma, apart from CDKN2A",{'G':(1.0,.5)}),
125:("Epidemiology of cutaneous melanoma incl. environmental and genetic (familial) factors",{'G':(.3,.5),'N':(.7,.75)}),
126:("ACAN variants cause aggrecan-related bone disorders incl. SEMD, familial osteochondritis dissecans and short stature with early osteoarthritis",{'P':(.4,.75),'G':(.6,1.0)}),
127:("IGF-1R antibody R1507 phase 2 across recurrent sarcoma subtypes incl. ASPS and synovial sarcoma",{'T':(1.0,.25)}),
128:("Trabectedin activity in translocation-related sarcomas incl. alveolar soft part and synovial sarcoma",{'M':(.5,.75),'T':(.5,.5)}),
129:("NY-ESO-1 expression high in synovial sarcoma, variable in other mesenchymal tumours",{'M':(.4,.25),'T':(.6,.25)}),
130:("Cabozantinib phase 1 in paediatric refractory solid tumours incl. ASPS and synovial sarcoma",{'T':(1.0,.5)}),
131:("Bevacizumab plus cediranib VEGF pathway dual inhibition phase 1 incl. ASPS and synovial sarcoma",{'T':(1.0,.5)}),
132:("WT1 donor splice-site mutations cause Frasier syndrome, related to Denys-Drash",{'P':(.4,.75),'G':(.6,1.0)}),
133:("Syndromic Wilms tumour review: Denys-Drash and Frasier predisposition, surveillance and treatment",{'G':(.2,1.0),'N':(.2,.75),'C':(.6,.75)}),
134:("Intronic WT1 exon 9 splicing mutations in Frasier syndrome versus Denys-Drash missense",{'G':(.7,1.0),'M':(.3,.75)}),
135:("Frasier syndrome as part of the Denys-Drash continuum or a WT1-associated disorder of sexual development",{'P':(.5,.75),'G':(.5,1.0)}),
136:("WT1 at the interface of kidney development and cancer; germline mutations cause DDS and Frasier syndromes",{'G':(.4,1.0),'M':(.6,.75)}),
137:("HPT-JT families linked to HRPT2 locus; parathyroid carcinoma is a component tumour of the syndrome",{'P':(.2,.5),'G':(.4,.75),'C':(.4,.75)}),
139:("Parafibromin tumour suppressor linked to both HPT-JT and sporadic parathyroid carcinoma",{'G':(.4,.75),'M':(.6,.75)}),
140:("HPT-JT operative management; risk of parathyroid carcinoma in HRPT2/CDC73 carriers",{'T':(.5,.5),'C':(.5,.6)}),
141:("Parafibromin and PGP9.5 IHC for diagnosis of parathyroid carcinoma; HRPT2 mutation link",{'G':(.4,.6),'D':(.6,.5)}),
142:("Prognostic factors for localized soft tissue sarcoma incl. synovial sarcoma and leiomyosarcoma",{'T':(.4,.5),'N':(.6,.5)}),
143:("Histotype-tailored versus standard neoadjuvant chemotherapy in high-risk soft tissue sarcoma (synovial sarcoma, leiomyosarcoma arms)",{'T':(1.0,.25)}),
144:("Anlotinib in refractory soft tissue sarcoma, leiomyosarcoma and synovial sarcoma cohorts",{'T':(1.0,.5)}),
145:("Wild-type p53 suppresses angiogenesis in leiomyosarcoma and synovial sarcoma",{'G':(.2,.5),'M':(.8,.75)}),
146:("TP53 roles across bone and soft tissue sarcomas",{'G':(.4,.5),'M':(.6,.5)}),
147:("Homozygosity mapping places AR CHED near the PPCD/CHED1 chromosome 20 region",{'P':(.3,.5),'G':(.7,.75)}),
148:("BMI differs between PHP1a and PPHP, both AHO with GNAS defects",{'P':(.5,.75),'G':(.3,1.0),'M':(.2,.75)}),
})
S.update({
150:("Novel GNAS mutation in PHP1A with normocalcemia; PHP1A and PPHP share GNAS loss of function",{'P':(.5,.75),'G':(.5,1.0)}),
151:("Synonymous GNAS exon 1 variant creating cryptic splice site in PHP1A/PPHP; maternal versus paternal allele",{'G':(.6,1.0),'M':(.4,.75)}),
152:("GNAS mutations in PHP1a and related disorders: maternal inheritance gives PHP1a, paternal gives PPHP",{'G':(.5,1.0),'M':(.5,.75)}),
153:("Regorafenib in bone sarcomas incl. Ewing sarcoma and chondrosarcoma cohorts",{'T':(1.0,.25)}),
156:("Immune checkpoint inhibitors in bone sarcomas incl. Ewing sarcoma and chondrosarcoma",{'T':(1.0,.25)}),
158:("Translational control of THPO via 5'UTR mutations causes hereditary thrombocythemia",{'G':(.5,.75),'M':(.5,.75)}),
159:("THPO splice-donor mutation in hereditary thrombocythemia, clinically resembling sporadic essential thrombocythemia",{'P':(.4,.75),'G':(.6,.5)}),
161:("Germline JAK2R564Q causes familial essential thrombocytosis, like acquired JAK2 MPN mutations",{'G':(.5,.5),'M':(.5,.75)}),
162:("Classification of paediatric myeloproliferative syndromes; essential thrombocythemia vs familial forms and overlapping conditions",{'P':(.4,.5),'D':(.6,.5)}),
163:("Peroxisome biogenesis disorders (ZS, NALD, IRD) genetics and cell biology",{'P':(.5,.9),'G':(.5,1.0)}),
164:("PEX1 mutations across ZS, NALD and IRD: severity tracks residual PEX1 protein",{'P':(.5,.75),'G':(.5,1.0)}),
165:("PBD patients with prolonged survival: phenotypic overlap of ZS, NALD and IRD",{'P':(.4,.75),'N':(.6,.75)}),
166:("Genotype-phenotype correlations in peroxisome biogenesis disorders (NALD, IRD)",{'P':(.4,.75),'G':(.6,1.0)}),
167:("PEX1-PEX6 interaction disruption is the most common cause of Zellweger spectrum disease",{'G':(.5,1.0),'M':(.5,1.0)}),
171:("Paediatric HCC genomics: is it closer to hepatoblastoma or adult HCC?",{'G':(.4,.5),'M':(.6,.5)}),
173:("FAK inhibition in hepatoblastoma; FAK also elevated in adult hepatocellular carcinoma",{'M':(1.0,.5)}),
174:("Sorafenib in paediatric HCC model compared with adult HCC and hepatoblastoma lines",{'M':(.3,.5),'T':(.7,.5)}),
176:("Caudal regression syndrome types include sirenomelia, complete and partial sacral agenesis",{'P':(1.0,.9)}),
177:("Caudal regression syndrome overview; sirenomelia a related condition; prevalence",{'P':(.6,.75),'N':(.4,.75)}),
178:("Sirenomelia as the most extreme form of caudal regression syndrome, in identical twins",{'P':(1.0,.9)}),
179:("Prenatal diagnosis of caudal regression: spectrum up to sirenomelia; shared maternal diabetes and vascular causes",{'P':(.6,.9),'M':(.4,.75)}),
180:("LCA and early-onset severe retinal dystrophy: shared clinical features and genetic heterogeneity",{'P':(.5,.9),'G':(.5,.9)}),
181:("RPE65-associated early-onset severe retinal dystrophy: longitudinal retinal function in LCA-type disease",{'G':(.4,.9),'N':(.6,.75)}),
182:("CRB1-associated retinal dystrophies incl. LCA and early-onset severe forms: natural history",{'G':(.4,.75),'N':(.6,.75)}),
183:("Natural history of retinal sensitivity in RPE65-associated LCA/EOSRD",{'N':(1.0,.75)}),
184:("rAAV2-RPE65 gene therapy in LCA and severe early-childhood-onset retinal degeneration",{'G':(.4,.9),'T':(.6,.9)}),
185:("SMAD3 mutations define a new aneurysm-osteoarthritis syndrome distinct from Marfan and Loeys-Dietz",{'P':(.5,.5),'G':(.5,.5)}),
186:("Differences in manifestations of Marfan, Ehlers-Danlos and Loeys-Dietz syndromes",{'P':(.5,.5),'D':(.5,.5)}),
188:("Genetic basis of thoracic aortic aneurysm incl. Marfan and Loeys-Dietz; smooth-muscle contractile gene focus",{'G':(.5,.5),'M':(.5,.5)}),
189:("SKI mutations cause Shprintzen-Goldberg syndrome; TGF-beta signalling in Marfan and Loeys-Dietz aneurysm",{'G':(.3,.5),'M':(.7,.75)}),
193:("Xp11 translocation RCC involves TFE3 fused to ASPL, the same gene fusion partner as alveolar soft part sarcoma",{'G':(.6,1.0),'M':(.4,.9)}),
194:("ASPSCR1-TFE3 driven mouse model gives both translocation RCC and alveolar soft part sarcoma",{'G':(.3,1.0),'M':(.7,.9)}),
195:("ASPSCR1-TFE3 fusion in PEComa-like neoplasms; TFE3 fusions in renal cell carcinoma and alveolar soft part sarcoma",{'G':(.6,1.0),'D':(.4,.5)}),
196:("TFE3 translocations occur in MiT translocation RCC and alveolar soft part sarcoma; TFE3 PEComa differential",{'G':(.6,.9),'D':(.4,.5)}),
198:("Pulsed dye laser treatment of keratosis pilaris atrophicans spectrum incl. atrophoderma vermiculata",{'P':(.3,.75),'T':(.7,.75)}),
199:("Lichenoid folliculitis unifying concept: KPA subgroup incl. atrophoderma vermiculatum and keratosis follicularis spinulosa decalvans",{'P':(.5,.75),'M':(.5,.75)}),
})
S.update({
201:("Atrophoderma vermiculatum, KPAF and KFSD are 3 variants of keratosis pilaris atrophicans, all hard to treat",{'P':(.7,.75),'T':(.3,.75)}),
207:("Ondine-Hirschsprung (Haddad) syndrome: CCHS with long-segment Hirschsprung disease, review of 17 cases",{'P':(.5,.75),'C':(.5,.9)}),
208:("CCHS associated with Hirschsprung disease configuring Haddad syndrome",{'C':(1.0,.9)}),
209:("Myectomy-myotomy for long-segment Hirschsprung disease in Haddad syndrome (CCHS plus HSCR)",{'T':(.6,.5),'C':(.4,.9)}),
210:("Down syndrome with both CCHS and Hirschsprung disease",{'C':(1.0,.75)}),
211:("PHOX2B polyalanine mutation alters neuronal progenitor transcriptome in CCHS; CCHS with HSCR is Haddad syndrome",{'G':(.5,.9),'M':(.5,.9)}),
212:("Telomere-driven diseases incl. DC and HH, and telomere-targeting therapies",{'M':(.6,.9),'T':(.4,.75)}),
213:("Biology and management of dyskeratosis congenita and related telomere biology disorders incl. Hoyeraal-Hreidarsson",{'P':(.3,.75),'G':(.3,.75),'T':(.4,.9)}),
214:("HH syndrome is a clinically severe variant of dyskeratosis congenita with early bone marrow failure death",{'P':(.4,.75),'G':(.3,.75),'N':(.3,.5)}),
215:("RTEL1 germline mutations in dyskeratosis congenita incl. severe HH variant",{'P':(.4,.75),'G':(.6,.75)}),
217:("Testicular seminoma and its mimics (incl. spermatocytic seminoma) on imaging and pathology",{'P':(.3,.5),'D':(.7,.5)}),
219:("20-year seminoma series incl. classic, anaplastic and spermatocytic seminoma outcomes",{'P':(.4,.5),'N':(.6,.5)}),
221:("Spermatocytic seminoma with sarcomatous transformation turns an innocuous tumour aggressive",{'M':(.4,.5),'N':(.6,.25)}),
222:("Ciliary skeletal disorders: Jeune syndrome and short rib-polydactyly type III are ciliopathies acting via hedgehog signalling",{'G':(.4,.75),'M':(.6,.75)}),
223:("Prenatal diagnosis of skeletal dysplasias incl. Jeune syndrome and short rib-polydactyly",{'P':(.2,.75),'D':(.8,.5)}),
224:("SALL4 mutations give clinically overlapping Okihiro, acro-renal-ocular and Holt-Oram phenotypes",{'P':(.5,.75),'G':(.5,1.0)}),
225:("SALL4-related disorders: DRRS (Okihiro), AROS and Holt-Oram, previously thought to be distinct",{'P':(.5,.75),'G':(.5,1.0)}),
226:("SALL4 mutations in Okihiro syndrome, acro-renal-ocular syndrome and related disorders",{'P':(.5,.75),'G':(.5,1.0)}),
227:("Family with SALL4 variant spanning upper limb, kidney and eye features of Okihiro/AROS/Holt-Oram",{'P':(.5,.75),'G':(.5,1.0)}),
229:("International study of pituitary gigantism: AIP mutations and familial isolated pituitary adenoma",{'P':(.4,.5),'G':(.6,.75)}),
230:("AIP mutations are most prevalent in gigantism (29%) and FIPA kindreds, rare in sporadic acromegaly",{'P':(.3,.5),'G':(.7,.75)}),
231:("Genetics of acromegaly and gigantism: AIP, GPR101, PRKAR1A and other germline/somatic causes",{'G':(.6,.75),'M':(.4,.5)}),
233:("Genetics of gigantism and acromegaly; familial pituitary adenoma genes",{'G':(.6,.75),'M':(.4,.5)}),
234:("FOXI3 pathogenic variants cause one form of craniofacial microsomia, also known as Goldenhar syndrome",{'P':(.5,.9),'G':(.5,.9)}),
236:("Birth prevalence of rare craniofacial anomalies incl. craniofacial microsomia and Goldenhar in Western Australia",{'P':(.2,.9),'N':(.8,.75)}),
238:("ROBO1 variation associated with craniofacial microsomia continuum incl. Goldenhar syndrome",{'P':(.5,.9),'G':(.5,.9)}),
243:("EWSR1-NFATC2 sarcoma overlaps immunomorphologically with Ewing sarcoma and extraskeletal myxoid chondrosarcoma",{'G':(.4,.5),'D':(.6,.5)}),
244:("CMT1A (PMP22 duplication) overview incl. Roussy-Levy presentation",{'P':(.5,.75),'G':(.5,.9)}),
246:("Ontology for SeLECTS and its atypical variants incl. Landau-Kleffner syndrome and ESES",{'P':(.6,.75),'N':(.4,.5)}),
247:("GRIN2A-related disorders span SeLECTS-like and Landau-Kleffner epilepsy-aphasia phenotypes",{'P':(.4,.75),'G':(.6,1.0)}),
248:("MEG source localisation across epilepsy-aphasia spectrum subtypes (SeLECTS, LKS, ESES)",{'P':(.4,.75),'M':(.6,.5)}),
249:("LGI1 mutations in ADPEAF, a familial temporal lobe epilepsy with auditory features",{'P':(.5,.75),'G':(.5,.9)}),
})
S.update({
250:("LGI1 missense mutation in familial temporal lobe epilepsy with aphasic seizures (auditory/aphasic ADLTE)",{'P':(.5,.75),'G':(.5,.9)}),
251:("Familial lateral temporal lobe epilepsy with aphasic seizures linked to 10q22-q24",{'P':(.6,.75),'G':(.4,.9)}),
252:("Mechanisms and management of inherited channelopathies (LQTS, Brugada, CPVT, short QT)",{'M':(.5,.5),'T':(.5,.5)}),
253:("Benign early repolarization versus malignant early abnormalities (Brugada, short QT) on ECG",{'D':(1.0,.5)}),
254:("ICD versus medical therapy for cardiac channelopathies incl. Brugada and short QT",{'T':(1.0,.5)}),
257:("Rituximab versus cyclophosphamide for ANCA vasculitis (GPA and MPA)",{'T':(1.0,.9)}),
258:("Genome-wide association: genetically distinct subsets within ANCA vasculitis (GPA vs MPA associated with different HLA/ANCA specificity)",{'G':(.7,.25),'M':(.3,.5)}),
259:("Long-term survival in ANCA vasculitis (Wegener's and microscopic polyangiitis)",{'N':(1.0,.75)}),
260:("2021 ACR/VF guideline for management of ANCA vasculitis incl. GPA and MPA",{'D':(.2,.5),'T':(.8,.9)}),
261:("Japanese AAV cohort classified into GPA and MPA by EMEA algorithm with serological features",{'P':(.5,.5),'D':(.5,.5)}),
262:("Novel EYA1 nonsense mutation in BOR/branchiootic syndrome; BO lacks renal anomalies",{'P':(.5,.75),'G':(.5,1.0)}),
263:("Branchio-otic syndrome with coexisting branchial fistulas; BOS differs from BOR by absent renal anomalies",{'P':(.6,.75),'D':(.4,.75)}),
264:("Branchio-otic syndrome from genomic rearrangement of EYA1; BOR genes EYA1, SIX1, SIX5",{'P':(.4,.75),'G':(.6,1.0)}),
265:("Cryptic EYA1 deletion-insertion in BOS patient; BOR spectrum disorder with or without renal anomalies",{'P':(.4,.75),'G':(.6,1.0)}),
266:("ILAE classification of childhood-onset epilepsy syndromes incl. EMAtS and Lennox-Gastaut",{'P':(.5,.5),'D':(.5,.5)}),
268:("Lennox-Gastaut and Doose syndromes once seen as one disease; community study tests continuum",{'P':(.4,.5),'N':(.6,.25)}),
269:("CHD2-related epilepsy phenotypes including myoclonic-atonic and Lennox-Gastaut-like presentations",{'P':(.5,.5),'G':(.5,.75)}),
270:("Parent survey of cannabidiol-enriched cannabis in treatment-resistant paediatric epilepsy incl. LGS and Doose syndrome",{'T':(1.0,.5)}),
271:("FTD with motor neuron disease equals ALS with dementia; shared medial temporal and hippocampal pathology",{'P':(.5,.9),'M':(.5,.75)}),
273:("Neuropsychiatric features of C9orf72-associated bvFTD and FTD-ALS",{'P':(.5,.75),'G':(.5,1.0)}),
275:("TCF7L1 immunostain differentiates testicular germ cell tumour types (seminoma versus yolk sac tumour)",{'M':(.2,.25),'D':(.8,.25)}),
276:("Synchronous bilateral testicular seminoma and yolk sac tumour",{'C':(1.0,.5)}),
277:("Ovarian dysgerminoma transformation to yolk sac tumour; analogous testicular seminoma transformation, histogenetic continuum",{'M':(.7,.75),'N':(.3,.5)}),
278:("Histologically pure seminoma with raised AFP: occult yolk sac tumour question",{'M':(.3,.5),'D':(.7,.5)}),
279:("Peroxisome biogenesis disorders (ZS, NALD, IRD) genetics and cell biology",{'P':(.5,.9),'G':(.5,1.0)}),
280:("PEX1 mutations across ZS, NALD and IRD: severity tracks residual PEX1 protein",{'P':(.5,.75),'G':(.5,1.0)}),
281:("PBD patients with prolonged survival: phenotypic overlap of ZS, NALD and IRD",{'P':(.4,.75),'N':(.6,.75)}),
282:("Genotype-phenotype correlations in peroxisome biogenesis disorders",{'P':(.4,.75),'G':(.6,1.0)}),
283:("PEX1-PEX6 interaction disruption is the most common cause of Zellweger spectrum disease",{'G':(.5,1.0),'M':(.5,1.0)}),
284:("Initial maximal motor ability predicts long-term outcome across COL6-related dystrophy phenotypes",{'P':(.4,.75),'N':(.6,.75)}),
285:("COL6-related dystrophies form a continuum from Bethlem through intermediate to Ullrich",{'P':(.5,.9),'G':(.5,1.0)}),
286:("B-K mole syndrome: familial melanomas arise from heritable atypical melanocytic lesions",{'P':(.5,.75),'C':(.5,.9)}),
288:("Dysplastic nevus syndrome phenotype in sporadic cutaneous melanoma",{'P':(.4,.75),'C':(.6,.75)}),
290:("Primary choroidal and cutaneous melanomas in a patient with B-K mole syndrome phenotype",{'C':(1.0,.5)}),
291:("PREPL deficiency phenotype; contiguous gene deletions involving PREPL, SLC3A1, CAMKMT, PPM1B",{'P':(.4,.75),'G':(.6,.75)}),
292:("Atypical hypotonia-cystinuria syndrome from C2orf34/PREPL/SLC3A1 deletion; HCS and 2p21 deletion syndromes compared",{'P':(.3,.75),'G':(.7,.75)}),
293:("PREPL gene lies within the 2p21 deletion and hypotonia-cystinuria syndromes",{'G':(.4,.75),'M':(.6,.75)}),
294:("Genotype-phenotype correlation in homozygous 2p21 deletion syndromes: overlapping deletions, distinct phenotypes",{'P':(.5,.5),'G':(.5,.75)}),
295:("Multi-system syndromes with cystinuria type I: 2p21 deletion, HCS and atypical HCS differ in genes lost",{'P':(.5,.5),'G':(.5,.75)}),
296:("PREPL deficiency phenotype and contiguous deletion syndromes (HCS, atypical HCS, 2p21 deletion)",{'P':(.4,.75),'G':(.6,.75)}),
297:("Genotype-phenotype correlation in homozygous 2p21 deletion syndromes",{'P':(.5,.5),'G':(.5,.75)}),
298:("Multi-system syndromes with cystinuria type I: 2p21 deletion versus atypical HCS",{'P':(.5,.5),'G':(.5,.75)}),
299:("C2orf34, PREPL and SLC3A1 deletion causes atypical HCS; 2p21 syndrome loses PPM1B too",{'P':(.4,.75),'G':(.6,.75)}),
})
S.update({
300:("Constitutional DICER1 mutations cause familial pleuropulmonary blastoma and a pleiotropic tumour syndrome",{'G':(.5,1.0),'C':(.5,.9)}),
301:("Pituitary blastoma as a pathognomonic feature of germline DICER1 (PPB-familial tumour and dysplasia syndrome)",{'G':(.4,1.0),'C':(.6,.75)}),
302:("DICER1 tumour predisposition syndrome initiated with pleuropulmonary blastoma, its most common tumour",{'G':(.4,1.0),'C':(.6,.9)}),
303:("Sporadic PHP1B case and review; PHP stratified into types 1A, 1B, 1C, 2 by GNAS genetic/epigenetic changes",{'P':(.5,.5),'G':(.5,.75)}),
304:("PHP1A due to GNAS exon A/B deletion with apparent loss of methylation, mimicking PHP1B",{'P':(.2,.6),'G':(.5,.75),'D':(.3,.7)}),
306:("GNAS imprinting defects with chromosome 2 deletions explain AHO features in PHP1B patients",{'P':(.5,.5),'G':(.5,.75)}),
307:("Chinese PHP1 cohort growth and short-stature patterns across PHP1A/1B genotypes",{'P':(.6,.75),'N':(.4,.75)}),
308:("SEPN1 mutations cause desmin-related myopathy with Mallory body-like inclusions, allelic to multiminicore disease",{'P':(.2,.6),'G':(.8,1.0)}),
309:("SEPN1 myopathies include rigid spine MD, multiminicore disease and MB-DRM; novel SEPN1 mutation",{'P':(.3,.6),'G':(.7,1.0)}),
310:("SEPN1-related myopathy manifests as multiminicore disease, MB-DRM or CFTD",{'P':(.3,.6),'G':(.7,1.0)}),
312:("MAKEI experience on malignant potential of teratomas in infancy and childhood versus yolk sac tumours",{'N':(.6,.5),'T':(.4,.5)}),
313:("Germline sequencing of Finnish familial germ cell tumour pedigrees (teratoma, yolk sac tumour and others)",{'P':(.3,.75),'G':(.7,.75)}),
314:("Bilateral infantile testicular teratoma; teratoma second only to yolk sac tumour in frequency in children",{'N':(1.0,.5)}),
316:("PRETEXT staging used to risk-stratify both hepatoblastoma and paediatric hepatocellular carcinoma",{'D':(.4,.5),'T':(.6,.75)}),
317:("Bcl-2 silencing and chemotherapy sensitivity in paediatric epithelial liver tumours (hepatoblastoma and HCC)",{'M':(.6,.75),'T':(.4,.75)}),
318:("SFRP1 downregulation and WNT/beta-catenin alteration shared by hepatoblastoma and paediatric HCC",{'G':(.3,.75),'M':(.7,.75)}),
321:("Crouzon syndrome with acanthosis nigricans (FGFR3 A391E) shows subtle achondroplasia-like radiographic findings",{'P':(.5,.75),'G':(.5,.5)}),
322:("FGFR2 A315S mild Crouzon phenotype; overlap with Crouzon-acanthosis nigricans (FGFR3) and Muenke",{'P':(.5,.75),'G':(.5,.5)}),
323:("X-linked retinopathies review incl. blue cone monochromacy and progressive cone dystrophy",{'P':(.5,.5),'G':(.5,.75)}),
325:("X-linked cone dystrophy mechanisms from red/green opsin missense mutations also found in blue cone monochromacy",{'G':(.4,.9),'M':(.6,.75)}),
326:("L/M opsin interchange mutants associated with BCM, cone degeneration, myopia; dual splicing/amino acid code",{'G':(.6,.9),'M':(.4,.75)}),
327:("LVAVA/MVAVA exon 3 interchange haplotypes: severity from myopia to BCM; late-onset progressive cone dystrophy",{'P':(.4,.75),'G':(.6,.9)}),
328:("Clinical and genetic differences between pustular psoriasis subtypes (GPP, PPP, ACH)",{'P':(.4,.5),'G':(.6,.25)}),
329:("Pustular psoriasis subtypes (GPP, palmoplantar, ACH) are phenotypically and genetically distinct, with new therapies",{'P':(.4,.5),'G':(.3,.5),'T':(.3,.5)}),
330:("IL36RN mutations underlie GPP, palmoplantar pustular psoriasis and ACH; genotype-phenotype correlation",{'P':(.4,.75),'G':(.6,.9)}),
333:("Consensus classification of ANCA vasculitis and PAN (EGPA, MPA) for epidemiology",{'D':(1.0,.5)}),
334:("Pathogenesis and therapy of ANCA vasculitis spanning MPA, GPA and EGPA",{'M':(.5,.75),'T':(.5,.75)}),
336:("ANCA testing consensus for Wegener's, MPA and Churg-Strauss: MPO versus PR3 patterns",{'D':(1.0,.5)}),
337:("ANCA-associated vasculitides GPA, MPA, EGPA as three separate but related conditions",{'P':(.4,.5),'M':(.3,.75),'T':(.3,.75)}),
338:("Sarcoma review: soft tissue (leiomyosarcoma) and primary bone (chondrosarcoma) sarcomas have different staging and treatment",{'T':(1.0,.25)}),
340:("TP53 roles across bone and soft tissue sarcomas",{'G':(.4,.5),'M':(.6,.5)}),
342:("Telomere lengths differ between translocation-associated and non-translocation sarcomas (complex karyotype group)",{'M':(1.0,.5)}),
343:("AIP mutation prevalence in young sporadic pituitary adenoma patients across subtypes",{'G':(1.0,.5)}),
344:("Re-irradiation outcomes for multiply recurrent pituitary adenomas of mixed subtype",{'T':(1.0,.75)}),
345:("Impulse control disorders in prolactinoma, acromegaly and non-functioning adenoma on or off dopamine agonists",{'T':(.6,.25),'C':(.4,.5)}),
346:("MEN1 prevalence in patients with pituitary tumours of different types (prolactinoma, non-functioning)",{'G':(.5,.5),'C':(.5,.5)}),
347:("Hyperprolactinemia pitfalls: serum prolactin cut-off does not reliably separate prolactinoma from non-functioning adenoma",{'D':(1.0,.5)}),
348:("Familial HUS associated with complement factor H deficiency",{'P':(.5,.75),'G':(.5,.9)}),
349:("Kidney transplantation in aHUS due to complement factor H mutations",{'G':(.3,.9),'T':(.7,.75)}),
})
S.update({
350:("Partial complement factor H deficiency associates with C3 glomerulopathy and thrombotic microangiopathy (aHUS)",{'G':(.6,.9),'C':(.4,.75)}),
351:("Living donor liver transplantation for complement factor H deficiency with aHUS",{'G':(.2,.9),'T':(.8,.75)}),
352:("CFH deficiency presenting with endocapillary GN; CFH mutations associated with aHUS, MPGN II and C3G",{'P':(.4,.5),'G':(.6,.9)}),
353:("Initial maximal motor ability predicts long-term outcome across COL6-related dystrophy phenotypes",{'P':(.4,.75),'N':(.6,.75)}),
354:("COL6-related dystrophies form a continuum from Bethlem through intermediate to Ullrich CMD",{'P':(.5,.9),'G':(.5,1.0)}),
355:("Pulsed dye laser treatment of keratosis pilaris atrophicans spectrum incl. ulerythema ophryogenes and atrophoderma vermiculata",{'P':(.3,.75),'T':(.7,.75)}),
356:("Lichenoid folliculitis unifying concept: KPA subgroup incl. ulerythema ophryogenes and atrophoderma vermiculatum",{'P':(.5,.75),'M':(.5,.75)}),
357:("Atrophoderma vermiculatum and KPAF/KFSD as variants of keratosis pilaris atrophicans, all hard to treat",{'P':(.7,.75),'T':(.3,.75)}),
358:("Proteomics of brain and CSF in three major forms of neuronal ceroid lipofuscinosis for biomarker discovery",{'M':(.6,.75),'D':(.4,.5)}),
359:("NCLs as related diseases sharing lipofuscin pathobiology but differing in anatomic onset and propagation",{'M':(.6,.75),'N':(.4,.5)}),
360:("Clinical course of 63 neonatal-onset urea cycle disorder patients incl. CPS1 and OTC deficiency",{'N':(.6,.75),'T':(.4,.75)}),
362:("Adult-onset diagnosis of urea cycle disorders in a French cohort (mainly OTC, also CPS1)",{'N':(.5,.75),'P':(.5,.75)}),
367:("Erythropoietic porphyrias (CEP, HEP, EPP): animal models and gene-based therapies",{'M':(.4,.75),'T':(.6,.75)}),
368:("Distinct distal myopathy phenotype in a large Finnish family with dominant inheritance",{'P':(.7,.75),'G':(.3,.5)}),
369:("Distal myopathies: Welander and tibial muscular dystrophy are clinically and genetically distinct entities",{'P':(.4,.5),'G':(.6,.25)}),
370:("Muscle MRI shows distinct diagnostic patterns in Welander distal myopathy versus tibial muscular dystrophy",{'P':(.3,.5),'D':(.7,.25)}),
371:("Distal muscular dystrophies: classification and differential diagnosis incl. Welander and tibial type",{'P':(.5,.5),'D':(.5,.5)}),
372:("Genotypic landscape of neuronal ceroid lipofuscinoses in Argentine children incl. CLN2 and CLN5",{'P':(.5,.75),'G':(.5,.25)}),
373:("Congenital platelet function disorders: Bernard-Soulier (GPIb-IX-V) and Glanzmann (integrin) glycoprotein defects",{'P':(.5,.75),'M':(.5,.5)}),
375:("Bleeding phenotype and diagnostic characterization of Glanzmann, Bernard-Soulier and other congenital platelet defects",{'P':(.6,.75),'D':(.4,.5)}),
376:("Inherited platelet disorders incl. Glanzmann and Bernard-Soulier: clinical and molecular phenotype, misdiagnosis risk",{'P':(.6,.75),'D':(.4,.5)}),
380:("Heme biosynthesis and the porphyrias; each porphyria defined by its specific enzyme defect",{'P':(.4,.75),'M':(.6,.9)}),
382:("Acute hepatic porphyrias (AIP, HCP, VP, ADP): pathogenesis and clinical features",{'P':(.4,.9),'G':(.3,.75),'M':(.3,.9)}),
383:("Best practice guidelines for acute porphyria attacks in AIP, VP and HCP",{'T':(1.0,.9)}),
385:("Molecular prenatal diagnosis across urea cycle defects incl. citrullinemia and OTC deficiency",{'G':(1.0,.5)}),
386:("Nationwide Japanese study of UCD long-term outcome and treatments",{'N':(.5,.75),'T':(.5,.75)}),
387:("Spanish UCD registry: natural history and effect of therapy and newborn screening",{'N':(.5,.75),'T':(.5,.75)}),
388:("Nutritional management and amino acid supplementation in urea cycle disorders on sodium phenylbutyrate",{'T':(1.0,.9)}),
389:("Clinical course of 63 neonatal-onset urea cycle disorder patients incl. citrullinemia and OTC deficiency",{'N':(.6,.75),'T':(.4,.75)}),
390:("Prevalence of congenital disaccharidase deficiencies (lactase, sucrase-isomaltase, trehalase) from allele frequencies",{'P':(.3,.75),'N':(.7,.5)}),
391:("Idiopathic inflammatory myopathies incl. polymyositis and antisynthetase syndrome: heterogeneous autoimmune group",{'P':(.4,.75),'N':(.3,.75),'T':(.3,.75)}),
392:("Classification and management of adult inflammatory myopathies (polymyositis, antisynthetase)",{'D':(.5,.5),'T':(.5,.75)}),
393:("Red cell membrane disorders pathogenesis incl. overhydrated stomatocytosis and Southeast Asian ovalocytosis",{'P':(.3,.5),'M':(.7,.5)}),
394:("Gene expression differentiates ovarian/primary peritoneal serous carcinoma from diffuse peritoneal mesothelioma",{'M':(.6,.25),'D':(.4,.25)}),
395:("Biological differences between ovarian serous carcinoma and diffuse peritoneal malignant mesothelioma",{'M':(.6,.25),'D':(.4,.25)}),
397:("Low-molecular-weight cyclin E differentiates ovarian carcinoma from mesothelial cells in effusions",{'M':(.3,.25),'D':(.7,.25)}),
398:("Peritoneal mesothelioma presenting as peritoneal carcinoma or ovarian cancer: differential diagnosis",{'P':(.2,.5),'D':(.8,.75)}),
399:("Clinical course of 63 neonatal-onset urea cycle disorder patients incl. CPS1 deficiency and citrullinemia",{'N':(.6,.75),'T':(.4,.75)}),
})
S.update({
400:("Reward circuitry dysfunction across neurodevelopmental/psychiatric disorders and genetic syndromes (PWS, Rett)",{'P':(.2,.5),'M':(.8,.5)}),
401:("Epigenetic disruption (imprinting in PWS, MeCP2 in Rett) in autism spectrum and neurodevelopmental disorders",{'G':(.2,.25),'M':(.8,.75)}),
403:("Pharmacotherapy of self-injurious behaviour across neurodevelopmental disorders incl. PWS and Rett",{'P':(.2,.5),'T':(.8,.5)}),
405:("Spectrum of ocular phenotypes caused by BEST1 mutations (Best disease, ADVIRC, ARB)",{'P':(.5,.75),'G':(.5,1.0)}),
406:("Mutation-dependent pathomechanisms determine phenotype across the bestrophinopathies (BD, ADVIRC, ARB)",{'G':(.4,1.0),'M':(.6,.75)}),
407:("ADVIRC is a BEST1 gain-of-function disease unlike loss-of-function/dominant-negative Best disease; photoreceptor changes compared",{'P':(.4,.25),'M':(.6,.25)}),
408:("Biallelic BEST1 mutation causes autosomal-recessive bestrophinopathy, distinct from dominant Best disease and ADVIRC",{'P':(.5,.5),'G':(.5,1.0)}),
409:("BEST1 causes five clinically distinct retinal diseases (bestrophinopathies) incl. Best disease and ADVIRC",{'P':(.5,.5),'G':(.5,1.0)}),
410:("Prior autoimmune disorders (incl. myositis) and risk of multiple myeloma/MGUS in US veterans",{'C':(1.0,.25)}),
411:("Autoimmune disease occurrence during IMiD treatment of myeloma",{'C':(1.0,.25)}),
412:("Haematological malignancy (incl. myeloma) associated with polymyositis/dermatomyositis",{'C':(1.0,.25)}),
414:("Autoimmune disease (incl. polymyositis) effect on incidence and survival of subsequent multiple myeloma",{'C':(1.0,.25)}),
415:("rMED with DTDST C653S; DTDST mutations span atelosteogenesis 2, achondrogenesis 1B, diastrophic dysplasia and rMED",{'P':(.4,.5),'G':(.6,1.0)}),
416:("DTDST sulfate transporter function and mutations causing four chondrodysplasias of varying severity",{'G':(.5,1.0),'M':(.5,.9)}),
418:("gsp-mediated GH excess in McCune-Albright syndrome with fibrous dysplasia; same GNAS activating mutations as sporadic acromegaly",{'G':(.6,.9),'C':(.4,.75)}),
419:("Pegvisomant for gsp-mediated GH excess in McCune-Albright syndrome; same mutations in one third of acromegaly",{'G':(.4,.9),'T':(.6,.75)}),
420:("Auxological and endocrine features in children with McCune-Albright syndrome incl. GH excess",{'C':(.6,.75),'N':(.4,.5)}),
421:("Albright syndrome (polyostotic fibrous dysplasia) associated with acromegaly: case and review",{'C':(1.0,.75)}),
422:("Adult McCune-Albright syndrome with fibrous dysplasia, cardiopulmonary complications and acromegaly",{'C':(1.0,.5)}),
423:("Chromophobe RCC arises sporadically and in genetic syndromes incl. Birt-Hogg-Dube and tuberous sclerosis complex",{'C':(1.0,.5)}),
424:("HSP90 in Birt-Hogg-Dube and tuberous sclerosis: chromophobe RCC versus angiomyolipoma, shared mTOR dysregulation",{'M':(.5,.5),'C':(.5,.5)}),
426:("Ewing sarcoma and peripheral PNET (Ewing tumours) share EWS/ets fusions detected by RT-PCR",{'P':(.4,.9),'G':(.6,1.0)}),
427:("Atypical pleomorphic extraosseous Ewing tumour/pPNET with unusual molecular features",{'P':(.5,.75),'G':(.5,.75)}),
429:("Porokeratotic eccrine nevus may be caused by somatic connexin26 mutations, the gene mutated in KID syndrome",{'P':(.3,.75),'G':(.7,.9)}),
434:("Small cell variant ALCL presenting as leukaemia, a mimic of T-cell leukaemias",{'P':(.4,.5),'D':(.6,.5)}),
436:("Cytogenetic guidelines for mature T- and NK-cell neoplasms with overlapping features (T-PLL, ALCL)",{'G':(.5,.25),'D':(.5,.5)}),
437:("Zika virus clinically resembles dengue fever; ZIKV lineage genetics",{'P':(.5,.75),'D':(.5,.75)}),
438:("Aedes aegypti vector competence for dengue, Zika, yellow fever and chikungunya viruses",{'M':(1.0,.75)}),
439:("Prior Zika infection enhances future risk of severe dengue (cross-reactive flavivirus immunity)",{'M':(.4,.75),'C':(.6,.5)}),
440:("Prior dengue infection and risk of Zika in a Nicaraguan paediatric cohort",{'M':(.4,.75),'C':(.6,.5)}),
441:("Dengue-reactive CD8 T cells cross-protect against subsequent Zika infection",{'M':(1.0,.75)}),
444:("Nutritional status (including obesity) in sarcoidosis patients and fatigue",{'C':(1.0,.5)}),
445:("Homozygous GJA1 mutation causes a Hallermann-Streiff/oculodentodigital dysplasia spectrum phenotype",{'P':(.5,.75),'G':(.5,.75)}),
446:("Hallermann-Streiff syndrome with nosologic overlap with oculodentodigital dysplasia",{'P':(.6,.75),'D':(.4,.75)}),
448:("Brain stem tumours (incl. astrocytomas) in neurofibromatosis type 1",{'C':(1.0,.5)}),
449:("Anaplastic astrocytoma in NF1 transforming into gliosarcoma after chemoradiation",{'C':(.6,.75),'N':(.4,.5)}),
})
S.update({
450:("Rare NF1 mutation in a Chinese NF1 patient with anaplastic astrocytoma",{'G':(.5,.5),'C':(.5,.75)}),
452:("Cerebellar anaplastic astrocytoma in an adult with NF1: case and review",{'C':(1.0,.75)}),
454:("EULAR/PReS classification criteria for childhood vasculitides incl. Kawasaki disease and PAN",{'D':(1.0,.5)}),
455:("CNS vasculitis imaging by vessel size: medium-vessel Kawasaki disease and polyarteritis nodosa",{'P':(.5,.75),'M':(.5,.5)}),
457:("Medium-size-vessel vasculitis in childhood: PAN, cutaneous PAN and Kawasaki disease",{'P':(.5,.75),'D':(.5,.5)}),
458:("Kawasaki disease compared with infantile and classic polyarteritis nodosa",{'P':(.6,.75),'D':(.4,.75)}),
459:("Lowe syndrome update: OCRL X-linked disorder with renal tubular dysfunction, related to Dent disease",{'P':(.5,.75),'G':(.5,1.0)}),
460:("OCRL suppresses intestinal TRPV6; OCRL mutations cause Lowe syndrome and Dent disease with hypercalciuria",{'G':(.3,1.0),'M':(.7,.75)}),
461:("Novel OCRL isoforms explain milder Dent disease-2 versus Lowe syndrome (exons 1-7 vs 8-24 truncations)",{'P':(.2,.5),'G':(.4,1.0),'M':(.4,.5)}),
462:("Endocytic proteins sharing an OCRL-binding motif with APPL1; Lowe and Dent disease share tubular defects",{'G':(.4,1.0),'M':(.6,.75)}),
463:("Kidney tubular Ocrl/Inpp5b ablation phenocopies Lowe/Dent proximal tubulopathy",{'P':(.4,.75),'M':(.6,.75)}),
464:("Chromothripsis in a Langer-Giedion patient characterised by long-read sequencing; overlap with CdLS region",{'G':(1.0,.25)}),
465:("Langer-Giedion, CdLS type 4 and hereditary multiple exostoses in one patient: RAD21 lies between TRPS1 and EXT1",{'P':(.4,.75),'G':(.6,.5)}),
467:("8q23.3-q24.22 deletion with Langer-Giedion features and CdLS-like phenotype in a patient initially misdiagnosed",{'P':(.5,.75),'G':(.5,.5)}),
469:("Biotin/thiamine-responsive basal ganglia disease (SLC19A3) as a treatable differential diagnosis of Leigh syndrome",{'D':(.7,.75),'T':(.3,.25)}),
470:("HER2-specific CAR T cells in recurrent sarcoma incl. Ewing/pPNET and DSRCT",{'T':(1.0,.5)}),
471:("Ewing sarcoma and Ewing-like tumours: molecular reappraisal of round cell sarcoma classification",{'G':(.5,.5),'D':(.5,.5)}),
473:("Ewing sarcoma/pPNET and related EWS-rearranged tumours (DSRCT) with overlapping features and diagnostic challenges",{'G':(.5,.75),'D':(.5,.75)}),
474:("Spectrum of EWSR1-rearranged neoplasms (Ewing, DSRCT, others) in 772 specimens",{'G':(.6,.75),'D':(.4,.5)}),
475:("Dura-based non-meningothelial lesions (solitary fibrous tumour, medulloblastoma) with overlapping imaging",{'D':(1.0,.25)}),
476:("Fatal hepatic angiosarcoma in an adolescent with dyskeratosis congenita",{'C':(1.0,.75)}),
477:("Liver pathology spectrum in dyskeratosis congenita incl. angiosarcoma",{'C':(1.0,.5)}),
478:("Second reported case of hepatic angiosarcoma arising in dyskeratosis congenita",{'C':(1.0,.75)}),
479:("Antibody-drug conjugate target expression across CNS tumours incl. pilocytic astrocytoma and CNS lymphoma",{'T':(1.0,.25)}),
482:("Nationwide survey of macular dystrophy incidence in Japan incl. occult macular dystrophy and Stargardt disease",{'N':(1.0,.5)}),
483:("STGD1 patients with central cone dysfunction resembling occult macular dystrophy",{'P':(.5,.75),'D':(.5,.9)}),
484:("Optical gap biomarker in cone-dominant retinal dystrophy incl. OMD and Stargardt",{'P':(.5,.5),'D':(.5,.5)}),
485:("Electrophysiological evaluation of macular dystrophies incl. Stargardt and occult macular dystrophy",{'D':(1.0,.5)}),
486:("Hodgkin disease in CLL; CLL may transform to plasma cell leukaemia or myeloma",{'C':(1.0,.5)}),
487:("Congenital corneal opacities review with genetics: CHSD and posterior polymorphous dystrophy",{'P':(.4,.75),'G':(.6,.5)}),
488:("ERCC1-XPF malfunction gives diverse manifestations incl. Cockayne syndrome and Fanconi anaemia features",{'P':(.4,.5),'G':(.6,.75)}),
489:("XPF defect with Cockayne syndrome features: persistence of repair proteins at lesions; XPF mutations also cause Fanconi anaemia",{'G':(.5,.75),'M':(.5,.75)}),
490:("ERCC4 mutations cause XP-F, Cockayne and Fanconi phenotypes and a cerebellar ataxia-dominant phenotype",{'P':(.4,.5),'G':(.6,.75)}),
491:("ERCC1/ERCC4 (XPF) nuclease genes in NER and interstrand crosslink repair underlie XP, CS and Fanconi anaemia",{'G':(.5,.75),'M':(.5,.75)}),
492:("ERCC4 variants in segmental progeroid syndromes; ERCC4 is also FANCQ",{'P':(.5,.5),'G':(.5,.75)}),
493:("Anakinra (IL-1 blockade) in cutaneous diseases incl. FMF and SAPHO syndrome",{'T':(1.0,.75)}),
495:("Prenatal Noonan syndrome gene testing in fetuses with abnormal ultrasound (e.g. hydrops, nuchal oedema)",{'C':(1.0,.5)}),
})
S.update({
501:("bcl-2 immunoreactivity across 380 spindle cell tumours incl. solitary fibrous tumour and GIST",{'M':(.3,.25),'D':(.7,.5)}),
502:("GIST on prostate needle biopsy: recognition among spindle cell tumours incl. solitary fibrous tumour",{'D':(1.0,.5)}),
503:("Immunohistochemical comparison of GIST and solitary fibrous tumour; overlapping clinicopathologic features",{'M':(.3,.25),'D':(.7,.75)}),
507:("Toxic epidermal necrolysis induced by tislelizumab in a patient with oesophageal squamous cell carcinoma",{'C':(1.0,.25)}),
509:("Tislelizumab-associated TEN in an oesophageal cancer patient",{'C':(1.0,.25)}),
511:("Splenic lymphoma with villous lymphocytes must be differentiated from hairy cell leukaemia, B-PLL and follicular lymphoma",{'D':(1.0,.5)}),
516:("External mandibular distraction for micrognathia and airway obstruction in Pierre Robin sequence and Moebius syndrome",{'P':(.5,.5),'T':(.5,.75)}),
522:("Sex differences across paediatric rheumatic diseases incl. Takayasu arteritis and juvenile dermatomyositis",{'N':(1.0,.5)}),
523:("Therapeutic plasma exchange in children with autoimmune diseases incl. Takayasu and juvenile dermatomyositis",{'T':(1.0,.5)}),
528:("Familial Mediterranean fever with IgA nephropathy: case report and review",{'C':(1.0,.75)}),
531:("High-resolution ultrasound of plantar skin in pachyonychia congenita compared with EPPK and mal de Meleda",{'P':(.5,.75),'D':(.5,.5)}),
532:("Neuroblastoma occurs in TP53 p.R337H carriers, who also develop adrenocortical tumours and choroid plexus carcinoma",{'G':(.5,.75),'C':(.5,.5)}),
533:("Olaparib plus irinotecan phase I/II in recurrent paediatric malignancies incl. neuroblastoma and choroid plexus carcinoma",{'T':(1.0,.25)}),
534:("Choroid plexus carcinoma CSF cytology compared with other small-cell childhood neoplasms such as neuroblastoma",{'D':(1.0,.25)}),
537:("Type II collagenopathies: achondrogenesis II, hypochondrogenesis, SEDC, Kniest dysplasia, Stickler as a COL2A1 spectrum",{'P':(.5,.75),'G':(.5,1.0)}),
538:("Novel COL2A1 splicing variant in achondrogenesis type II; COL2A1 spectrum incl. Kniest",{'P':(.3,.5),'G':(.7,1.0)}),
539:("Dominant COL2A1 mutations produce SEMD, Kniest and achondrogenesis-hypochondrogenesis spectrum of chondrodysplasias",{'P':(.4,.5),'G':(.6,1.0)}),
541:("COL2A1 splice mutation in SEDC: phenotypic continuum of type II collagen chondrodysplasias incl. achondrogenesis II and Kniest",{'P':(.5,.75),'G':(.5,1.0)}),
542:("Paternal-age-effect disorders (achondroplasia FGFR3, Apert FGFR2) and selfish spermatogonial selection",{'G':(.4,.5),'M':(.6,.9)}),
544:("Selfish spermatogonial selection links advanced paternal age to de novo PAE disorders such as achondroplasia and Apert",{'M':(1.0,.9)}),
545:("Cellular evidence for selfish spermatogonial selection in aged testes: PAE disorders achondroplasia and Apert syndrome",{'M':(1.0,.9)}),
549:("Myeloproliferative neoplasms: CML (BCR-ABL1) and polycythemia vera (JAK2) as classic MPNs",{'G':(.4,.25),'M':(.4,.5),'T':(.2,.5)}),
})
S.update({
551:("2016 WHO classification and diagnostic criteria for myeloproliferative neoplasms incl. CML and polycythemia vera",{'P':(.5,.5),'D':(.5,.75)}),
552:("Purple skin diseases: vasculitides (EGPA) and vasculopathies (TTP) in a differential review",{'D':(1.0,.25)}),
553:("EBV-positive post-transplant lymphoproliferative disorder presenting as primary CNS diffuse large B-cell lymphoma",{'D':(.5,.75),'C':(.5,.9)}),
558:("Childhood cancer incidence in sub-Saharan Africa: Burkitt lymphoma and retinoblastoma among leading cancers",{'N':(1.0,.5)}),
560:("ENPP1 mutation causes generalized arterial calcification of infancy; ENPP1 phenotypes incl. PXE and Cole disease",{'P':(.4,.5),'G':(.6,.75)}),
561:("ENPP1 variant update across pathologic calcification, hypophosphatemic rickets, PXE and Cole disease",{'G':(.6,.75),'M':(.4,.75)}),
562:("Anti-Hsp90/70 antibodies in children with SLE, juvenile dermatomyositis and juvenile arthritis",{'M':(1.0,.5)}),
564:("Amphotericin B spectrum and resistance across fungal pathogens incl. coccidioidomycosis and zygomycosis",{'T':(1.0,.75)}),
565:("Fungal infections (coccidioidomycosis, mucormycosis and others) misdiagnosed as tuberculosis",{'D':(1.0,.75)}),
570:("Pyrin SPRY domain (FMF) interacts with inflammasome components shared with cryopyrin diseases such as Muckle-Wells",{'G':(.3,.25),'M':(.7,.75)}),
572:("Molecular genetics of hereditary autoinflammatory diseases: FMF (MEFV) and Muckle-Wells (NLRP3)",{'G':(.5,.25),'M':(.5,.75)}),
573:("Monogenic autoinflammatory syndromes: genetic, clinical and therapeutic overview incl. FMF and Muckle-Wells",{'P':(.3,.75),'G':(.3,.25),'M':(.4,.75)}),
574:("Pyrin, the FMF gene product, regulates cryopyrin/Pypaf1 signalling mutated in Muckle-Wells",{'M':(1.0,.75)}),
575:("Recent advances in antifungal chemotherapy for invasive fungal infections incl. chromomycosis and fusariosis",{'T':(1.0,.5)}),
576:("Posaconazole prophylaxis and treatment of fungal infections incl. fusariosis and chromoblastomycosis",{'T':(1.0,.75)}),
577:("Posaconazole in refractory invasive fungal infections incl. fusariosis and chromoblastomycosis",{'T':(1.0,.75)}),
582:("Therapeutic management of mitochondrial disorders incl. LHON and Friedreich ataxia",{'M':(.3,.75),'T':(.7,.5)}),
583:("Pentamidine treats antimony-resistant leishmaniasis and Pneumocystis pneumonia",{'T':(1.0,.75)}),
584:("Visceral Leishmania braziliensis in an HIV patient with Pneumocystis pneumonia",{'C':(1.0,.5)}),
587:("Pentamidine-induced long QT; drug used for leishmaniasis, trypanosomiasis and Pneumocystis pneumonia",{'T':(1.0,.75)}),
588:("Itraconazole review: broad antifungal incl. chromomycosis and coccidioidomycosis",{'T':(1.0,.75)}),
589:("Fungal infections (coccidioidomycosis, chromoblastomycosis and others) misdiagnosed as tuberculosis",{'D':(1.0,.75)}),
590:("NGS pathogen detection in FFPE tissue from chromoblastomycosis, coccidioidomycosis and other tropical infections",{'D':(1.0,.5)}),
591:("Posaconazole activity in refractory invasive fungal infections incl. chromomycosis and coccidioidomycosis",{'T':(1.0,.75)}),
592:("70-year histology review of deep fungal infections in Uganda incl. chromoblastomycosis and coccidioidomycosis",{'N':(1.0,.5)}),
593:("Invasive fungal infections in organ transplant recipients: aspergillosis and cryptococcosis burden (TRANSNET)",{'N':(1.0,.5)}),
594:("Population-based analysis of invasive fungal infections in France incl. aspergillosis and cryptococcosis",{'N':(1.0,.5)}),
595:("Incidence and direct cost of systemic fungal infections (aspergillosis, cryptococcosis)",{'N':(1.0,.5)}),
596:("Calcineurin in fungal virulence and drug resistance in Aspergillus, Candida and Cryptococcus",{'M':(.6,.75),'T':(.4,.75)}),
597:("Flucytosine pharmacology and clinical use in cryptococcosis and aspergillosis combination therapy",{'T':(1.0,.5)}),
598:("Immunohistochemical diagnosis of systemic mycoses incl. fusariosis and coccidioidomycosis",{'D':(1.0,.5)}),
599:("Posaconazole in phase III trials for aspergillosis, coccidioidomycosis and fusariosis",{'T':(1.0,.75)}),
})
S.update({
600:("Posaconazole prophylaxis/treatment spanning fusariosis and coccidioidomycosis among other mycoses",{'T':(1.0,.75)}),
601:("Posaconazole in refractory invasive fungal infections incl. fusariosis and coccidioidomycosis",{'T':(1.0,.75)}),
603:("Endotoxin hyperreactivity and tolerance in volunteers with typhoid fever and tularemia",{'M':(1.0,.75)}),
605:("Typhoidal tularemia in an adolescent with pancytopenia and pericarditis, mimicking typhoid/haematological malignancy",{'P':(.3,.75),'D':(.7,.75)}),
608:("10-year Nigerian review of morbidity from EPI-preventable diseases incl. whooping cough and poliomyelitis",{'N':(1.0,.5)}),
611:("Pertussis toxin hypothesis for harmful effects and prolonged immunity of whooping cough, like bacterial exotoxins such as diphtheria toxin",{'M':(1.0,.5)}),
613:("ARH3 structure and reversibility of ADP-ribosylation by bacterial toxins causing whooping cough and diphtheria",{'M':(1.0,.75)}),
614:("Cellular uptake of bacterial AB-type toxins causing cholera, whooping cough and diphtheria",{'M':(1.0,.75)}),
616:("Typhoid incidence among febrile illnesses in Egypt incl. brucellosis",{'N':(.6,.5),'D':(.4,.75)}),
617:("Prevalence of bacterial febrile illnesses in Tanzanian children incl. brucellosis and typhoid",{'N':(.6,.5),'D':(.4,.75)}),
618:("Brucellosis as a cause of acute febrile illness in Egypt alongside typhoid",{'N':(.4,.5),'D':(.6,.75)}),
621:("Pulmonary abnormalities in Klippel-Trenaunay syndrome with lymphangioleiomyomatosis-like features",{'P':(.4,.5),'C':(.6,.5)}),
622:("Invasive fungal infections in transplant recipients: aspergillosis and zygomycosis burden (TRANSNET)",{'N':(1.0,.5)}),
623:("Delaying amphotericin B-based therapy increases mortality in zygomycosis",{'T':(.7,.5),'N':(.3,.25)}),
624:("Zygomycosis rise in the era of Aspergillus-active voriconazole therapy; compared with invasive aspergillosis",{'T':(.5,.25),'C':(.5,.5)}),
625:("Pharmacokinetics of antifungals for aspergillosis and zygomycosis; amphotericin B active against both",{'T':(1.0,.5)}),
626:("Zygomycosis as re-emerging infection in immunocompromised hosts alongside aspergillosis",{'N':(.6,.5),'C':(.4,.5)}),
627:("SEIFEM-2004: incidence and outcome of invasive fungal infections incl. fusariosis and zygomycosis in haematological malignancy",{'N':(1.0,.5)}),
628:("Liposomal amphotericin B active against Zygomycetes and other moulds incl. Fusarium",{'T':(1.0,.75)}),
629:("Rare mould infections (Mucorales, Lomentospora, Fusarium) epidemiology and outcomes in San Diego",{'N':(1.0,.75)}),
630:("qPCR discrimination of aspergillosis, mucormycosis, fusariosis and scedosporiosis in FFPE tissue",{'D':(1.0,.5)}),
632:("Cryopyrin activates the inflammasome in response to toxins and ATP; mutated in cold urticaria and Muckle-Wells",{'M':(1.0,.9)}),
633:("NALP3/CIAS1 mutations link Muckle-Wells, familial cold autoinflammatory syndrome and CINCA; role in innate immunity",{'G':(.5,1.0),'M':(.5,.9)}),
634:("De novo CIAS1 mutations in NOMID, the gene that causes Muckle-Wells and familial cold urticaria",{'G':(1.0,.9)}),
635:("CINCA syndrome caused by CIAS1 mutations, the gene for Muckle-Wells and familial cold urticaria",{'G':(1.0,.9)}),
636:("Ketone metabolite beta-hydroxybutyrate blocks NLRP3-mediated disease models of FCAS and Muckle-Wells",{'M':(.5,.9),'T':(.5,.75)}),
637:("JAK2 gain-of-function mutation in polycythemia vera, essential thrombocythemia and myelofibrosis",{'G':(.6,.9),'M':(.4,.9)}),
638:("MPLW515L activating mutation in myelofibrosis; JAK2V617F in PV, ET and MF",{'G':(.7,.5),'M':(.3,.9)}),
639:("JAK1/2 inhibitor INCB018424 preclinical activity in JAK2V617F MPN incl. PV and ET",{'T':(1.0,.9)}),
640:("JAK2 exon 12 mutations in V617F-negative polycythemia vera; V617F in PV, ET and myelofibrosis",{'G':(1.0,.75)}),
641:("Activating JAK2V617F mutation in PV, ET and idiopathic myelofibrosis",{'G':(.6,1.0),'M':(.4,.9)}),
643:("Penicillamine-induced elastosis perforans serpiginosa in Wilson disease; penicillamine also used in cystinuria",{'T':(.7,.9),'C':(.3,.25)}),
644:("D-penicillamine-induced EPS reported in Wilson disease and cystinuria",{'T':(1.0,.9)}),
645:("Penicillamine clinical uses (Wilson disease, cystinuria, RA) and cutaneous adverse effects",{'T':(1.0,.9)}),
646:("D-penicillamine used for Wilson disease and cystinuria can cause myasthenia gravis",{'T':(1.0,.9)}),
647:("Chitotriosidase screening in children with organomegaly to diagnose Gaucher, Niemann-Pick A/B and C",{'D':(1.0,.75)}),
649:("Distribution and demographics of lysosomal storage disorder subtypes in Eastern China incl. Gaucher and Niemann-Pick",{'N':(1.0,.5)}),
})
S.update({
650:("Gaucher markers chitotriosidase and CCL18 raised in type B Niemann-Pick: similar storage macrophages",{'P':(.3,.75),'M':(.4,.75),'D':(.3,.75)}),
652:("Dapsone used for dermatitis herpetiformis and Hansen's disease (leprosy); gel pharmacokinetics",{'T':(1.0,.75)}),
653:("Historical morbidity/mortality comparisons for vaccine-preventable diseases incl. diphtheria and poliomyelitis",{'N':(.5,.5),'T':(.5,.75)}),
658:("Aetiology of adult bronchiectasis: ABPA and primary ciliary dyskinesia among causes",{'C':(1.0,.5)}),
659:("Non-CF bronchiectasis in adults: causes include ABPA and primary ciliary dyskinesia",{'C':(1.0,.5)}),
661:("Adolescent with asthma and bronchiectasis: differential diagnosis includes ABPA and primary ciliary dyskinesia",{'D':(1.0,.5)}),
668:("Nephrocalcinosis aetiology in Indian children: distal RTA in 50%, idiopathic hypercalciuria also",{'D':(.5,.5),'C':(.5,.5)}),
669:("Renal acidification testing in children with idiopathic hypercalciuria; dRTA frequently associated with hypercalciuria",{'M':(.3,.5),'C':(.7,.5)}),
671:("Urinary citrate reduced in distal RTA but normal in idiopathic hypercalciuria",{'M':(.4,.25),'D':(.6,.25)}),
675:("Vasculitis, including cutaneous small-vessel vasculitis, associated with VEXAS syndrome",{'C':(1.0,.75)}),
678:("Comparative pharmacology of albendazole, praziquantel etc. for cysticercosis and echinococcosis",{'T':(1.0,.9)}),
679:("Cestode vaccines against Taenia solium (cysticercosis) and Echinococcus granulosus",{'T':(1.0,.75)}),
682:("Inherited arterial calcification syndromes incl. GACI and CD73-deficiency arterial/joint calcification",{'G':(.4,.5),'M':(.6,.75)}),
683:("Pseudoxanthoma elasticum prototype of ectopic mineralisation with overlap with GACI and CD73 deficiency; low PPi/Pi ratio",{'M':(.5,.75),'T':(.5,.75)}),
684:("Heritable ectopic mineralisation disorders: PXE, GACI and arterial calcification due to CD73 deficiency",{'P':(.5,.75),'M':(.5,.75)}),
685:("Genetics of arterial calcification from rare diseases GACI, PXE, CALJA and basal ganglia calcification",{'G':(.5,.5),'M':(.5,.75)}),
686:("Therapeutics development for PXE and related ectopic mineralisation disorders incl. GACI and CD73 deficiency",{'T':(.6,.75),'M':(.4,.75)}),
689:("Molecular vaccines against parasites incl. bovine babesiosis and cysticercosis in sheep and cattle",{'T':(1.0,.25)}),
693:("Eosinophilic lung diseases: chronic eosinophilic pneumonia versus other eosinophilic disorders incl. ABPA",{'P':(.5,.75),'D':(.5,.75)}),
694:("D2-40 immunohistochemistry in paediatric vascular tumours and malformations differentiates kaposiform haemangioendothelioma",{'D':(1.0,.25)}),
695:("Anticoagulation in left ventricular noncompaction and peripartum cardiomyopathy: systematic review",{'T':(1.0,.75)}),
696:("Peripartum cardiomyopathy with left ventricular noncompaction features in a haemodialysis patient",{'D':(.6,.75),'C':(.4,.9)}),
})
